# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build PIK
        run: |
          powershell -c "Write-Host 'Combining files...'
          powershell -file .\Build_no_Run.ps1
          powershell -c "Write-Host 'Output:';Write-Host (GC -ReadCount 0 .\pik.ps1 | Out-String)"
          
      - uses: EndBug/add-and-commit@v6.2.0
        with:
          # Arguments for the git add command
          add: ./pik.ps1 # optional, default is .

          # The name of the user that will be displayed as the author of the commit
          author_name: tastykayks # optional
          # The email of the user that will be displayed as the author of the commit
          
          # Name of the branch to use, if different from the one that triggered the workflow
          branch: master # optional
          # The directory where your repository is located. You should use actions/checkout first to set it up

          message: Standard build by runner # optional
          # The flag used on the pull strategy
